site_name: Maxine SRD
nav:
  - Introduction: index.md
  - Features: features.md
  - Getting started: about.md
  - API: api.md
  - LICENCE: licence.md
  - About: about.md
theme:
  name: readthedocs
  nav_style: dark
  highlightjs: true
plugins:
  - swagger-ui-tag:
      background: white
site_dir: buildocs
