site_name: Maxine SRD

nav:
    - Introduction: index.md
    - Features: features.md
    - Getting started: about.md
    - API: about.md
    - About: about.md

theme:
  name: readthedocs
  nav_style: dark
  # highlightjs: true
  # hljs_languages:
  #     - yaml
  #     - rust
site_dir: build/docs