site_name: Maxine SRD

nav:
    - Introduction: index.md
    - Features: features.md
    - Getting started: about.md
    - API: about.md
    - LICENCE: licence.md
    - About: about.md

theme:
  name: readthedocs
  nav_style: dark
  highlightjs: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx

markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition

site_dir: buildocs
