site_name: Maxine SRD

nav:
    - Introduction: index.md
    - Features: features.md
    - Getting started: about.md
    - API: about.md
    - LICENCE: licence.md
    - About: about.md

theme:
  name: readthedocs
  nav_style: dark

site_dir: build/docs
