version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6
  grafana: grafana/k6@1.1.3

jobs:
  checkout_source:
    docker:
      - image: circleci/node:14.15.1-stretch
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .
  install_dependencies:
    docker:
      - image: circleci/node:14.15.1-stretch
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - node_modules/*
  test:
    docker:
      - image: circleci/node:14.15.1-stretch
    parallelism: 8
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          command: |
            circleci tests glob 'test/**/*.test.js' |
            circleci tests split |
            npm run coverage
      - store_test_results:
          path: .

      - store_artifacts:
          path: artifacts

workflows:
  build_and_utest:
    jobs:
      - checkout_source
      - install_dependencies:
          requires:
            - checkout_source
      - test:
          requires:
            - install_dependencies
  deploy_and_ltest:
    jobs:
      - heroku/deploy-via-git
      - grafana/k6:
          requires:
            - heroku/deploy-via-git
          script: src/test/load-test/performance-test.js